-- Схема EDO (на основе ERD pgAdmin). Выполняется при первом создании volume Postgres.
-- ENUM-типы в исходном экспорте не были включены — добавлены здесь.

BEGIN;

-- ---------------------------------------------------------------------------
-- ENUM (отсутствовали в экспорте ERD)
-- ---------------------------------------------------------------------------
CREATE TYPE public.applicant_type_enum AS ENUM (
    'PHYSICAL_PERSON',
    'LEGAL_ENTITY',
    'INDIVIDUAL_ENTREPRENEUR'
);

CREATE TYPE public.appeal_type_enum AS ENUM (
    'COMPLAINT',
    'APPLICATION',
    'REQUEST',
    'OTHER'
);

CREATE TYPE public.appeal_priority_enum AS ENUM (
    'LOW',
    'NORMAL',
    'HIGH',
    'URGENT'
);

CREATE TYPE public.incident_status_enum AS ENUM (
    'NEW',
    'ASSIGNED',
    'IN_PROGRESS',
    'RESOLVED',
    'CLOSED'
);

-- ---------------------------------------------------------------------------
-- Таблицы (порядок по внешним ключам)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.roles
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name        character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role_description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active        boolean NOT NULL,
    created_at       timestamp(0) with time zone NOT NULL,
    created_by       bigint NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.statuses
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_name        character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status_description text COLLATE pg_catalog."default" NOT NULL,
    is_active          boolean NOT NULL,
    created_at         timestamp(0) with time zone NOT NULL,
    created_by         timestamp(0) with time zone NOT NULL,
    CONSTRAINT statuses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_templates
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at    timestamp(0) with time zone NOT NULL,
    created_by    bigint NOT NULL,
    CONSTRAINT audit_templates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  character(255) COLLATE pg_catalog."default" NOT NULL,
    last_name   character(255) COLLATE pg_catalog."default" NOT NULL,
    patronymic  character(255) COLLATE pg_catalog."default" NOT NULL,
    "position"  character(255) COLLATE pg_catalog."default" NOT NULL,
    role_id     bigint NOT NULL,
    new_column  bigint NOT NULL,
    is_active   boolean NOT NULL,
    created_at  timestamp(0) with time zone NOT NULL,
    created_by  bigint NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.audit
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    started_at         timestamp(0) with time zone NOT NULL,
    user_id            bigint NOT NULL,
    audit_template_id  bigint NOT NULL,
    CONSTRAINT audit_pkey PRIMARY KEY (id),
    CONSTRAINT audit_audit_template_id_foreign FOREIGN KEY (audit_template_id)
        REFERENCES public.audit_templates (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.appeals
(
    id                       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    letter_number            integer NOT NULL,
    letter_received_at       timestamp(0) with time zone NOT NULL,
    applicant_type           public.applicant_type_enum NOT NULL,
    appeal_type              public.appeal_type_enum NOT NULL,
    appeal_category_id       bigint NOT NULL,
    appeal_subcategory_id    bigint NOT NULL,
    appeal_priority          public.appeal_priority_enum NOT NULL,
    applicant_id             bigint NOT NULL,
    appeal_description       text COLLATE pg_catalog."default" NOT NULL,
    appeal_status            bigint NOT NULL,
    user_id                  bigint NOT NULL,
    answer_id                bigint NOT NULL,
    commission_decision_id   bigint NOT NULL,
    created_at               timestamp(0) with time zone NOT NULL,
    created_by               bigint NOT NULL,
    planned_processing_at    timestamp(0) with time zone NOT NULL,
    processed_at             timestamp(0) with time zone NOT NULL,
    audit_id                 bigint NOT NULL,
    CONSTRAINT appeals_pkey PRIMARY KEY (id),
    CONSTRAINT appeals_appeal_status_foreign FOREIGN KEY (appeal_status)
        REFERENCES public.statuses (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT appeals_audit_id_foreign FOREIGN KEY (audit_id)
        REFERENCES public.audit (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT appeals_user_id_foreign FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.attachments
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appeal_id         bigint NOT NULL,
    s3_key            character varying(255) COLLATE pg_catalog."default" NOT NULL,
    original_filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type      character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_size         bigint NOT NULL,
    uploaded_at       timestamp(0) with time zone NOT NULL,
    uploaded_by       bigint NOT NULL,
    CONSTRAINT attachments_pkey PRIMARY KEY (id),
    CONSTRAINT attachments_appeal_id_foreign FOREIGN KEY (appeal_id)
        REFERENCES public.appeals (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.audit_questions
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id          bigint NOT NULL,
    question_description bigint NOT NULL,
    created_at           timestamp(0) with time zone NOT NULL,
    created_by           bigint NOT NULL,
    CONSTRAINT audit_questions_pkey PRIMARY KEY (id),
    CONSTRAINT audit_questions_template_id_foreign FOREIGN KEY (template_id)
        REFERENCES public.audit_templates (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.feedback
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    audit_id     bigint NOT NULL,
    assessment   bigint NOT NULL,
    question_id  bigint NOT NULL,
    answer       text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT feedback_pkey PRIMARY KEY (id),
    CONSTRAINT feedback_audit_id_foreign FOREIGN KEY (audit_id)
        REFERENCES public.audit (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.incidents
(
    id                      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appeal_id               bigint NOT NULL,
    created_at              timestamp(0) with time zone NOT NULL,
    target_resolution_date  timestamp(0) with time zone NOT NULL,
    applicant_full_name     character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applicant_phone         character varying(255) COLLATE pg_catalog."default" NOT NULL,
    appeal_description      text COLLATE pg_catalog."default" NOT NULL,
    user_comments             text COLLATE pg_catalog."default" NOT NULL,
    attachment_id           bigint NOT NULL,
    incident_processed_at   timestamp(0) with time zone NOT NULL,
    hd_user_id              bigint NOT NULL,
    incident_status         public.incident_status_enum NOT NULL,
    CONSTRAINT incidents_pkey PRIMARY KEY (id),
    CONSTRAINT incidents_appeal_id_foreign FOREIGN KEY (appeal_id)
        REFERENCES public.appeals (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.requests_to_business_units
(
    id                             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                     timestamp(0) with time zone NOT NULL,
    created_by                     bigint NOT NULL,
    request_planned_processing_date timestamp(0) with time zone NOT NULL,
    request_processed_at          timestamp(0) with time zone NOT NULL,
    request_answer                 text COLLATE pg_catalog."default" NOT NULL,
    bu_comment                     text COLLATE pg_catalog."default" NOT NULL,
    appeal_id                      bigint NOT NULL,
    CONSTRAINT requests_to_business_units_pkey PRIMARY KEY (id),
    CONSTRAINT requests_to_business_units_appeal_id_foreign FOREIGN KEY (appeal_id)
        REFERENCES public.appeals (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.users_roles
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (id),
    CONSTRAINT users_roles_role_id_foreign FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT users_roles_user_id_foreign FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

COMMIT;
